# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: openjdk:24-slim-bullseye
  # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Compile the Java program
      - name: Compile Java
        run: |
          javac Hello.java

      # Create an artifact for the compiled .class file
      - name: Upload Hello.class as artifact
        uses: actions/upload-artifact@v3
        with:
          name: hello-class
          path: Hello.class
            
      - uses: actions/download-artifact@v4
        with:
          path: artifacts/Hello.class
      - name: Run Java program
        run: |
          java Hello
